version: "3.7"

services:
    verifier-mock:
        image: clojure:openjdk-14-alpine
        volumes:
            - "../..:/app"
        working_dir: /app
        environment:
            LEIN_REPL_HOST: "0.0.0.0"
            LEIN_REPL_PORT: 6661
        expose:
            - "9000"
            - "6661"
        ports:
            - "6661:6661"
            - "8000:8000"
        command: ["lein", "run"]
